### ISSUE TITLE
gitbook build时出错！

### ISSUE THREAD

**Issue by szdastone** [liushilive/gitbook-plugin-books#3]
TypeError: Cannot read property 'content' of undefined
--

TypeError: Cannot read property 'content' of undefined                               at Object.hooks_page (C:\Users\user\.nodejs\node_global\node_modules\books-c li\lib\sectionx.js:9:24)                                                             at Object.page (D:\git_workspace\Gitbook-User-Manual\node_modules\gitbook-pl ugin-books\index.js:61:39)                                                           at C:\Users\user\.gitbook\versions\3.2.3\lib\output\callHook.js:48:29            at C:\Users\user\.gitbook\versions\3.2.3\lib\utils\promise.js:22:20              at _fulfilled (C:\Users\user\.gitbook\versions\3.2.3\node_modules\q\q.js:834 :54)                                                                                 at C:\Users\user\.gitbook\versions\3.2.3\node_modules\q\q.js:863:30              at Promise.promise.promiseDispatch (C:\Users\user\.gitbook\versions\3.2.3\no de_modules\q\q.js:796:13)                                                            at C:\Users\user\.gitbook\versions\3.2.3\node_modules\q\q.js:556:49              at runSingle (C:\Users\user\.gitbook\versions\3.2.3\node_modules\q\q.js:137: 13)                                                                                  at flush (C:\Users\user\.gitbook\versions\3.2.3\node_modules\q\q.js:125:13)  error: error while generating page "README.md":                                                                                                                   TypeError: Cannot read property 'content' of undefined
--

**Comment by liushilive** [comment]
使用 `gitbook build . --log debug` 构建，查看报错信息，具体是哪个页面。

如果可以还请提供新的报错信息，以及该页面的内容。

初步确认是 `README.md` 文件中无内容导致。

**Comment by szdastone** [comment]
![books.png](https://i.loli.net/2019/01/18/5c4138860f39c.png)
直接上图片吧，我昨天将代码中sectionx有关的删除了，然后一切正常。
不应该是README.md无内容，所有的都是有内容的！

**Comment by szdastone** [comment]
谢谢，最新版本已经解决了。
